hide_display_names = true
use_nerdfont = true
flip_status_indicators = false
[theme]
#background = "black"
primary = "light white"
secondary = "light blue"
title = "green"
playing = "green"
playing_selected = "light green"
playing_bg = "glight blue"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
